/* BERZAN — Çok dilli sistem (Google YOK; kendi sözlüğümüz)
   - Metin düğümlerini çevirir, ikon/sembollere (material-symbols, .notranslate) DOKUNMAZ
   - Anında geçiş, localStorage'da kalıcı, RTL (ar/fa) desteği
   - Yeni dil eklemek: LANGS'e [kod,ad] + T sözlüğüne o kodun karşılıkları */
(function () {
  "use strict";

  // Sırası dropdown'da görünür. Sadece sözlüğü olan diller listelenir.
  var LANGS = [
    ["tr", "Türkçe"], ["en", "English"], ["de", "Deutsch"], ["fr", "Français"],
    ["es", "Español"], ["ru", "Русский"], ["ar", "العربية"], ["ku", "Kurdî"]
  ];
  var RTL = { ar: 1, fa: 1 };

  // Türkçe metin -> { dil: çeviri }
  var T = {
"Tedarik Alanları":{en:"Supply Areas",de:"Lieferbereiche",fr:"Domaines de fourniture",es:"Áreas de suministro",ru:"Категории поставок",ar:"مجالات التوريد",ku:"Warên Peydakirinê"},
"Nasıl Çalışıyoruz":{en:"How It Works",de:"So funktioniert es",fr:"Comment ça marche",es:"Cómo funciona",ru:"Как это работает",ar:"كيف نعمل",ku:"Em Çawa Dixebitin"},
"Nasıl Çalışıyoruz?":{en:"How It Works?",de:"Wie funktioniert es?",fr:"Comment ça marche ?",es:"¿Cómo funciona?",ru:"Как это работает?",ar:"كيف نعمل؟",ku:"Em Çawa Dixebitin?"},
"Neden BERZAN":{en:"Why BERZAN",de:"Warum BERZAN",fr:"Pourquoi BERZAN",es:"Por qué BERZAN",ru:"Почему BERZAN",ar:"لماذا بيرزان",ku:"Çima BERZAN"},
"Referanslar":{en:"References",de:"Referenzen",fr:"Références",es:"Referencias",ru:"Рекомендации",ar:"المراجع",ku:"Referans"},
"İletişim":{en:"Contact",de:"Kontakt",fr:"Contact",es:"Contacto",ru:"Контакты",ar:"اتصل بنا",ku:"Têkilî"},
"Teklif Alın":{en:"Get a Quote",de:"Angebot anfordern",fr:"Demander un devis",es:"Solicitar presupuesto",ru:"Получить предложение",ar:"اطلب عرض سعر",ku:"Pêşniyarê Bistîne"},
"KURUMSAL TEDARİK ÇÖZÜMLERİ":{en:"CORPORATE PROCUREMENT SOLUTIONS",de:"BESCHAFFUNGSLÖSUNGEN FÜR UNTERNEHMEN",fr:"SOLUTIONS D'APPROVISIONNEMENT POUR ENTREPRISES",es:"SOLUCIONES DE COMPRAS CORPORATIVAS",ru:"КОРПОРАТИВНЫЕ РЕШЕНИЯ ПО СНАБЖЕНИЮ",ar:"حلول التوريد للشركات",ku:"ÇARESERIYÊN PEYDAKIRINA KORPORATÎF"},
"Kurumsal alımlarınızda tek tedarik noktası":{en:"A single supply point for your corporate purchasing",de:"Ein zentraler Beschaffungspunkt für Ihre Unternehmenseinkäufe",fr:"Un point d'approvisionnement unique pour vos achats d'entreprise",es:"Un único punto de suministro para sus compras corporativas",ru:"Единая точка снабжения для корпоративных закупок",ar:"نقطة توريد واحدة لمشترياتكم المؤسسية",ku:"Ji bo kirînên we yên korporatîf xala peydakirinê ya yekane"},
"BERZAN, şirketlerin operasyonel ihtiyaçlarını karşılamak için uçtan uca tedarik yönetimi sağlar. Tek muhatap ve tek fatura ile karmaşıklığı ortadan kaldırıyor, maliyetlerinizi optimize ediyoruz.":{en:"BERZAN provides end-to-end procurement management to meet companies' operational needs. With a single point of contact and a single invoice, we remove complexity and optimize your costs.",de:"BERZAN bietet durchgängiges Beschaffungsmanagement für die betrieblichen Anforderungen von Unternehmen. Mit einem einzigen Ansprechpartner und einer einzigen Rechnung beseitigen wir Komplexität und optimieren Ihre Kosten.",fr:"BERZAN assure une gestion des achats de bout en bout pour répondre aux besoins opérationnels des entreprises. Avec un interlocuteur unique et une facture unique, nous supprimons la complexité et optimisons vos coûts.",es:"BERZAN ofrece una gestión integral de compras para cubrir las necesidades operativas de las empresas. Con un único interlocutor y una única factura, eliminamos la complejidad y optimizamos sus costes.",ru:"BERZAN обеспечивает комплексное управление закупками под операционные нужды компаний. Единый контакт и единый счёт устраняют сложность и оптимизируют ваши расходы.",ar:"تقدّم بيرزان إدارة توريد متكاملة لتلبية الاحتياجات التشغيلية للشركات. بفضل جهة اتصال واحدة وفاتورة واحدة، نزيل التعقيد ونحسّن تكاليفكم.",ku:"BERZAN ji bo bersivdana hewcedariyên xebatî yên şirketan rêveberiya peydakirinê ya seranser pêşkêş dike. Bi yek navbeynkar û yek fatûreyê, em aloziyê radikin û lêçûnên we baştir dikin."},
"Tedarikçi Olun":{en:"Become a Supplier",de:"Lieferant werden",fr:"Devenir fournisseur",es:"Conviértase en proveedor",ru:"Стать поставщиком",ar:"كن مورّداً",ku:"Bibe Peydakar"},
"Ücretsiz & hızlı teklif":{en:"Free & fast quote",de:"Kostenloses & schnelles Angebot",fr:"Devis gratuit et rapide",es:"Presupuesto gratuito y rápido",ru:"Бесплатное и быстрое предложение",ar:"عرض سعر مجاني وسريع",ku:"Pêşniyara bê pere û bilez"},
"Tek muhatap, tek fatura":{en:"One contact, one invoice",de:"Ein Ansprechpartner, eine Rechnung",fr:"Un interlocuteur, une facture",es:"Un interlocutor, una factura",ru:"Один контакт, один счёт",ar:"جهة اتصال واحدة، فاتورة واحدة",ku:"Yek navbeynkar, yek fatûre"},
"Türkiye geneli teslimat":{en:"Delivery across Türkiye",de:"Lieferung in der ganzen Türkei",fr:"Livraison dans toute la Turquie",es:"Entrega en toda Türkiye",ru:"Доставка по всей Турции",ar:"توصيل في جميع أنحاء تركيا",ku:"Şandin li seranserê Tirkiyeyê"},
"Tedarikçi":{en:"Suppliers",de:"Lieferanten",fr:"Fournisseurs",es:"Proveedores",ru:"Поставщиков",ar:"مورّد",ku:"Peydakar"},
"Tamamlanan Talep":{en:"Completed Requests",de:"Abgeschlossene Anfragen",fr:"Demandes traitées",es:"Solicitudes completadas",ru:"Выполненных заявок",ar:"طلبات مُنجزة",ku:"Daxwazên Temamkirî"},
"4 Saat":{en:"4 Hours",de:"4 Stunden",fr:"4 heures",es:"4 horas",ru:"4 часа",ar:"4 ساعات",ku:"4 Saet"},
"Ort. Teklif Süresi":{en:"Avg. Quote Time",de:"Durchschn. Angebotszeit",fr:"Délai moyen de devis",es:"Tiempo medio de oferta",ru:"Среднее время ответа",ar:"متوسط زمن عرض السعر",ku:"Navînî Dema Pêşniyarê"},
"Kurumsal Müşteri":{en:"Corporate Clients",de:"Firmenkunden",fr:"Clients entreprises",es:"Clientes corporativos",ru:"Корпоративных клиентов",ar:"عميل مؤسسي",ku:"Xerîdarên Korporatîf"},
"Tedarik Alanlarımız":{en:"Our Supply Areas",de:"Unsere Lieferbereiche",fr:"Nos domaines de fourniture",es:"Nuestras áreas de suministro",ru:"Наши категории поставок",ar:"مجالات التوريد لدينا",ku:"Warên Me yên Peydakirinê"},
"Başlıca alanlar — bunlarla sınırlı değiliz. İhtiyacınız ne olursa olsun kaynak araştırması yapıyoruz.":{en:"Main areas — we are not limited to these. Whatever you need, we research the source for you.",de:"Hauptbereiche — wir sind nicht darauf beschränkt. Was immer Sie brauchen, wir recherchieren die Quelle für Sie.",fr:"Principaux domaines — nous ne nous y limitons pas. Quel que soit votre besoin, nous recherchons la source pour vous.",es:"Áreas principales: no nos limitamos a ellas. Sea cual sea su necesidad, buscamos la fuente por usted.",ru:"Основные направления — мы не ограничиваемся ими. Что бы вам ни понадобилось, мы найдём источник.",ar:"المجالات الرئيسية — ولسنا مقتصرين عليها. مهما كان احتياجكم، نبحث لكم عن المصدر.",ku:"Warên sereke — em bi van re sînorkirî nînin. Hewcedariya we çi dibe bila bibe, em ji bo we çavkaniyê lêdikolin."},
"Matbaa & Baskı":{en:"Printing & Press",de:"Druck & Druckerei",fr:"Imprimerie & impression",es:"Imprenta e impresión",ru:"Полиграфия и печать",ar:"المطبعة والطباعة",ku:"Çapxane & Çap"},
"Kurumsal kimlik materyallerinden, katalog ve form basımlarına kadar tüm matbaa çözümleri.":{en:"All printing solutions, from corporate identity materials to catalogs and form printing.",de:"Alle Drucklösungen, von Corporate-Identity-Materialien bis zu Katalogen und Formulardruck.",fr:"Toutes les solutions d'impression, des supports d'identité visuelle aux catalogues et imprimés.",es:"Todas las soluciones de impresión, desde materiales de identidad corporativa hasta catálogos e impresos.",ru:"Все полиграфические решения — от фирменного стиля до каталогов и бланков.",ar:"جميع حلول الطباعة، من مواد الهوية المؤسسية إلى الكتالوجات والنماذج.",ku:"Hemû çareseriyên çapê, ji materyalên nasnameya korporatîf heta katalog û çapên forman."},
"Promosyon Ürünleri":{en:"Promotional Products",de:"Werbeartikel",fr:"Produits promotionnels",es:"Productos promocionales",ru:"Промопродукция",ar:"المنتجات الترويجية",ku:"Berhemên Promosyonê"},
"Marka değerinizi artıracak, logo baskılı geniş ürün yelpazesi ve özel tasarım seçenekleri.":{en:"A wide range of logo-printed products and custom design options to boost your brand value.",de:"Eine breite Palette logo­bedruckter Produkte und individuelle Designoptionen, um Ihren Markenwert zu steigern.",fr:"Une large gamme de produits imprimés à votre logo et des options de design sur mesure pour valoriser votre marque.",es:"Una amplia gama de productos con su logotipo y opciones de diseño personalizado para potenciar su marca.",ru:"Широкий ассортимент продукции с логотипом и индивидуальный дизайн для роста ценности бренда.",ar:"تشكيلة واسعة من المنتجات المطبوع عليها شعاركم وخيارات تصميم خاصة لتعزيز قيمة علامتكم.",ku:"Cûrbecûr berhemên bi logo çapkirî û bijarên sêwirana taybet ji bo zêdekirina nirxa marqaya we."},
"Ambalaj & Poşet":{en:"Packaging & Bags",de:"Verpackung & Beutel",fr:"Emballage & sacs",es:"Embalaje y bolsas",ru:"Упаковка и пакеты",ar:"التغليف والأكياس",ku:"Pakkirin & Tûr"},
"Ürünleriniz için koruyucu ambalajlar, özel baskılı koliler ve farklı materyallerde poşet çözümleri.":{en:"Protective packaging, custom-printed boxes and bag solutions in various materials for your products.",de:"Schutzverpackungen, individuell bedruckte Kartons und Beutellösungen in verschiedenen Materialien für Ihre Produkte.",fr:"Emballages de protection, cartons imprimés sur mesure et solutions de sacs en différents matériaux pour vos produits.",es:"Embalajes protectores, cajas impresas a medida y soluciones de bolsas en distintos materiales para sus productos.",ru:"Защитная упаковка, коробки с печатью на заказ и пакеты из различных материалов для вашей продукции.",ar:"تغليف واقٍ وصناديق بطباعة مخصّصة وحلول أكياس بمواد متنوّعة لمنتجاتكم.",ku:"Pakkirina parastinê, qutiyên bi çapa taybet û çareseriyên tûran bi materyalên cuda ji bo berhemên we."},
"Tekstil & İş Kıyafeti":{en:"Textile & Workwear",de:"Textil & Arbeitskleidung",fr:"Textile & vêtements de travail",es:"Textil y ropa de trabajo",ru:"Текстиль и спецодежда",ar:"المنسوجات وملابس العمل",ku:"Tekstîl & Cilûbergên Kar"},
"Personel kıyafetleri, tişörtler, önlükler ve kurumsal tekstil ihtiyaçlarınızda yüksek kalite.":{en:"High quality in staff uniforms, t-shirts, aprons and all your corporate textile needs.",de:"Hohe Qualität bei Personalkleidung, T-Shirts, Schürzen und all Ihren Unternehmens-Textilien.",fr:"Une haute qualité pour les tenues du personnel, t-shirts, tabliers et tous vos besoins textiles d'entreprise.",es:"Alta calidad en uniformes de personal, camisetas, delantales y todas sus necesidades textiles corporativas.",ru:"Высокое качество форменной одежды, футболок, фартуков и любого корпоративного текстиля.",ar:"جودة عالية في ملابس الموظفين والقمصان والمرايل وجميع احتياجاتكم النسيجية المؤسسية.",ku:"Kalîteya bilind di cilên personelan, tîşort, pêşmal û hemû hewcedariyên we yên tekstîla korporatîf de."},
"İş Güvenliği (KKD)":{en:"Occupational Safety (PPE)",de:"Arbeitssicherheit (PSA)",fr:"Sécurité au travail (EPI)",es:"Seguridad laboral (EPI)",ru:"Охрана труда (СИЗ)",ar:"السلامة المهنية (معدات الوقاية)",ku:"Ewlehiya Kar (KKD)"},
"Yönetmeliklere uygun kişisel koruyucu donanımlar ve güvenlik ekipmanları tedariği.":{en:"Supply of regulation-compliant personal protective equipment and safety gear.",de:"Lieferung von vorschriftskonformer persönlicher Schutzausrüstung und Sicherheitsausstattung.",fr:"Fourniture d'équipements de protection individuelle et de sécurité conformes à la réglementation.",es:"Suministro de equipos de protección individual y de seguridad conformes a la normativa.",ru:"Поставка средств индивидуальной защиты и оборудования безопасности по нормативам.",ar:"توريد معدّات الوقاية الشخصية ومعدّات السلامة المطابقة للوائح.",ku:"Peydakirina amûrên parastina kesane û amûrên ewlehiyê yên li gorî rêziknameyan."},
"Ofis & Kırtasiye":{en:"Office & Stationery",de:"Büro & Schreibwaren",fr:"Bureau & papeterie",es:"Oficina y papelería",ru:"Офис и канцелярия",ar:"المكتب والقرطاسية",ku:"Ofîs & Qirtasiye"},
"Günlük ofis işleyişiniz için gerekli tüm kırtasiye malzemeleri ve ofis sarf malzemeleri.":{en:"All stationery and office consumables needed for your daily office operations.",de:"Alle Schreibwaren und Büroverbrauchsmaterialien für Ihren täglichen Bürobetrieb.",fr:"Toute la papeterie et les consommables de bureau nécessaires à votre fonctionnement quotidien.",es:"Toda la papelería y los consumibles de oficina necesarios para su funcionamiento diario.",ru:"Вся канцелярия и расходные материалы для ежедневной работы офиса.",ar:"جميع القرطاسية ومستلزمات المكتب اللازمة لعملكم اليومي.",ku:"Hemû qirtasiye û pêdiviyên ofîsê yên ji bo xebata we ya rojane."},
"4 adımda verimli tedarik süreci":{en:"An efficient procurement process in 4 steps",de:"Ein effizienter Beschaffungsprozess in 4 Schritten",fr:"Un processus d'approvisionnement efficace en 4 étapes",es:"Un proceso de compras eficiente en 4 pasos",ru:"Эффективный процесс закупок за 4 шага",ar:"عملية توريد فعّالة في 4 خطوات",ku:"Pêvajoya peydakirinê ya bibandor di 4 gavan de"},
"Talep":{en:"Request",de:"Anfrage",fr:"Demande",es:"Solicitud",ru:"Заявка",ar:"الطلب",ku:"Daxwaz"},
"İhtiyaçlarınızı formumuz üzerinden veya müşteri temsilcinize iletin.":{en:"Send us your needs via our form or through your account representative.",de:"Teilen Sie uns Ihre Bedürfnisse über unser Formular oder Ihren Kundenbetreuer mit.",fr:"Communiquez vos besoins via notre formulaire ou votre conseiller dédié.",es:"Envíenos sus necesidades a través de nuestro formulario o de su representante.",ru:"Сообщите о потребностях через форму или вашего менеджера.",ar:"أرسلوا لنا احتياجاتكم عبر النموذج أو من خلال ممثّل الحساب.",ku:"Hewcedariyên xwe bi forma me an jî bi nûnerê xwe re ji me re bişînin."},
"Fiyat Toplama":{en:"Collecting Quotes",de:"Angebote einholen",fr:"Collecte des devis",es:"Recopilación de ofertas",ru:"Сбор предложений",ar:"جمع العروض",ku:"Berhevkirina Bihayan"},
"Geniş tedarikçi ağımızdan sizin için en rekabetçi fiyatları topluyoruz.":{en:"We collect the most competitive prices for you from our wide supplier network.",de:"Wir holen für Sie die wettbewerbsfähigsten Preise aus unserem großen Lieferantennetzwerk ein.",fr:"Nous collectons pour vous les prix les plus compétitifs auprès de notre vaste réseau de fournisseurs.",es:"Recopilamos para usted los precios más competitivos de nuestra amplia red de proveedores.",ru:"Мы собираем для вас самые выгодные цены из нашей широкой сети поставщиков.",ar:"نجمع لكم أكثر الأسعار تنافسيةً من شبكة مورّدينا الواسعة.",ku:"Em ji tora xwe ya berfireh a peydakaran bihayên herî pêşbazî ji bo we berhev dikin."},
"En Uygun Teklif":{en:"Best Quote",de:"Bestes Angebot",fr:"Meilleure offre",es:"Mejor oferta",ru:"Лучшее предложение",ar:"أفضل عرض",ku:"Pêşniyara Herî Guncaw"},
"Onayınıza sunulan karşılaştırmalı tekliflerden size uygun olanı seçin.":{en:"Choose the one that suits you from the comparative quotes presented for your approval.",de:"Wählen Sie aus den zur Genehmigung vorgelegten Vergleichsangeboten das passende aus.",fr:"Choisissez l'offre qui vous convient parmi les devis comparatifs soumis à votre approbation.",es:"Elija la que más le convenga entre las ofertas comparativas presentadas para su aprobación.",ru:"Выберите подходящее из сравнительных предложений, представленных на ваше утверждение.",ar:"اختاروا ما يناسبكم من العروض المقارنة المقدّمة لموافقتكم.",ku:"Ji pêşniyarên berawirdkirî yên ji bo erêkirina we hatine pêşkêşkirin ya guncaw hilbijêre."},
"Teslim & Takip":{en:"Delivery & Tracking",de:"Lieferung & Verfolgung",fr:"Livraison & suivi",es:"Entrega y seguimiento",ru:"Доставка и отслеживание",ar:"التسليم والمتابعة",ku:"Şandin & Şopandin"},
"Siparişiniz kapınıza kadar gelirken tüm süreci biz takip edelim.":{en:"Let us track the whole process while your order arrives at your door.",de:"Wir verfolgen den gesamten Prozess, während Ihre Bestellung bis vor Ihre Tür gelangt.",fr:"Laissez-nous suivre tout le processus pendant que votre commande arrive jusqu'à votre porte.",es:"Deje que sigamos todo el proceso mientras su pedido llega hasta su puerta.",ru:"Мы отслеживаем весь процесс, пока заказ не прибудет к вашей двери.",ar:"دعونا نتابع العملية بأكملها بينما يصل طلبكم إلى بابكم.",ku:"Bila em tevahiya pêvajoyê bişopînin dema ku sîpariça we digihîje ber deriyê we."},
"NEDEN BİZ?":{en:"WHY US?",de:"WARUM WIR?",fr:"POURQUOI NOUS ?",es:"¿POR QUÉ NOSOTROS?",ru:"ПОЧЕМУ МЫ?",ar:"لماذا نحن؟",ku:"ÇIMA EM?"},
"Tedarik Zincirinde Güven ve Hız":{en:"Trust and Speed in the Supply Chain",de:"Vertrauen und Geschwindigkeit in der Lieferkette",fr:"Confiance et rapidité dans la chaîne d'approvisionnement",es:"Confianza y rapidez en la cadena de suministro",ru:"Надёжность и скорость в цепочке поставок",ar:"الثقة والسرعة في سلسلة التوريد",ku:"Pêbawerî û Bilezî di Zincîra Peydakirinê de"},
"BERZAN, operasyonel yüklerinizi hafifletmek ve maliyetlerinizi düşürmek için tasarlanmış profesyonel bir ekosistemdir.":{en:"BERZAN is a professional ecosystem designed to ease your operational burden and lower your costs.",de:"BERZAN ist ein professionelles Ökosystem, das Ihre operative Last verringert und Ihre Kosten senkt.",fr:"BERZAN est un écosystème professionnel conçu pour alléger votre charge opérationnelle et réduire vos coûts.",es:"BERZAN es un ecosistema profesional diseñado para aliviar su carga operativa y reducir sus costes.",ru:"BERZAN — это профессиональная экосистема, созданная, чтобы снизить операционную нагрузку и расходы.",ar:"بيرزان منظومة احترافية مصمّمة لتخفيف العبء التشغيلي وخفض تكاليفكم.",ku:"BERZAN ekosîstemeke profesyonel e ku ji bo sivikkirina barê we yê xebatî û kêmkirina lêçûnên we hatiye sêwirandin."},
"Tek Nokta":{en:"Single Point",de:"Zentrale Anlaufstelle",fr:"Point unique",es:"Punto único",ru:"Единая точка",ar:"نقطة واحدة",ku:"Xala Yekane"},
"Yüzlerce tedarikçi yerine tek muhatap ile tüm operasyonu yönetin.":{en:"Manage the entire operation with a single contact instead of hundreds of suppliers.",de:"Steuern Sie den gesamten Ablauf mit einem einzigen Ansprechpartner statt Hunderten Lieferanten.",fr:"Gérez toute l'opération avec un seul interlocuteur au lieu de centaines de fournisseurs.",es:"Gestione toda la operación con un único interlocutor en lugar de cientos de proveedores.",ru:"Управляйте всей операцией через один контакт вместо сотен поставщиков.",ar:"أديروا العملية بأكملها عبر جهة اتصال واحدة بدلاً من مئات المورّدين.",ku:"Tevahiya operasyonê bi yek navbeynkar li şûna sed peydakaran birêve bibe."},
"En Uygun Fiyat":{en:"Best Price",de:"Bester Preis",fr:"Meilleur prix",es:"Mejor precio",ru:"Лучшая цена",ar:"أفضل سعر",ku:"Bihayê Herî Guncaw"},
"Çoklu teklif toplama mekanizmamız ile her zaman en rekabetçi fiyatı alın.":{en:"Always get the most competitive price thanks to our multi-quote mechanism.",de:"Erhalten Sie dank unseres Mehrfachangebots-Mechanismus stets den wettbewerbsfähigsten Preis.",fr:"Obtenez toujours le prix le plus compétitif grâce à notre mécanisme multi-devis.",es:"Obtenga siempre el precio más competitivo gracias a nuestro mecanismo de múltiples ofertas.",ru:"Всегда получайте лучшую цену благодаря механизму сбора нескольких предложений.",ar:"احصلوا دائماً على أكثر الأسعار تنافسيةً بفضل آلية العروض المتعدّدة لدينا.",ku:"Bi mekanîzmaya me ya berhevkirina gelek pêşniyaran her dem bihayê herî pêşbazî bistîne."},
"Geniş Tedarikçi Ağı":{en:"Wide Supplier Network",de:"Großes Lieferantennetzwerk",fr:"Vaste réseau de fournisseurs",es:"Amplia red de proveedores",ru:"Широкая сеть поставщиков",ar:"شبكة مورّدين واسعة",ku:"Tora Peydakaran a Berfireh"},
"Türkiye'nin dört bir yanındaki onaylı ve güvenilir üretim partnerleri.":{en:"Approved and reliable manufacturing partners across Türkiye.",de:"Geprüfte und zuverlässige Produktionspartner in der ganzen Türkei.",fr:"Des partenaires de fabrication agréés et fiables dans toute la Turquie.",es:"Socios de fabricación aprobados y fiables en toda Türkiye.",ru:"Проверенные и надёжные производственные партнёры по всей Турции.",ar:"شركاء تصنيع معتمدون وموثوقون في جميع أنحاء تركيا.",ku:"Hevkarên hilberînê yên pejirandî û pêbawer li seranserê Tirkiyeyê."},
"Hızlı & Ücretsiz Teklif":{en:"Fast & Free Quote",de:"Schnelles & kostenloses Angebot",fr:"Devis rapide et gratuit",es:"Presupuesto rápido y gratuito",ru:"Быстрое и бесплатное предложение",ar:"عرض سعر سريع ومجاني",ku:"Pêşniyara Bilez û Bê Pere"},
"Talepleriniz için hiçbir ücret ödemeden saatler içinde tekliflerinizi alın.":{en:"Get your quotes within hours, with no fee for your requests.",de:"Erhalten Sie Ihre Angebote innerhalb von Stunden – ohne Gebühr für Ihre Anfragen.",fr:"Recevez vos devis en quelques heures, sans frais pour vos demandes.",es:"Reciba sus presupuestos en horas, sin coste por sus solicitudes.",ru:"Получайте предложения за считанные часы и без платы за заявки.",ar:"احصلوا على عروضكم خلال ساعات ودون أي رسوم على طلباتكم.",ku:"Ji bo daxwazên xwe bê tu lêçûn di nav saetan de pêşniyarên xwe bistînin."},
"Şeffaf Süreç":{en:"Transparent Process",de:"Transparenter Prozess",fr:"Processus transparent",es:"Proceso transparente",ru:"Прозрачный процесс",ar:"عملية شفّافة",ku:"Pêvajoya Zelal"},
"Siparişinizin durumunu anlık olarak izleyin ve detaylı raporlar alın.":{en:"Track your order status in real time and receive detailed reports.",de:"Verfolgen Sie Ihren Bestellstatus in Echtzeit und erhalten Sie detaillierte Berichte.",fr:"Suivez l'état de votre commande en temps réel et recevez des rapports détaillés.",es:"Siga el estado de su pedido en tiempo real y reciba informes detallados.",ru:"Отслеживайте статус заказа в реальном времени и получайте подробные отчёты.",ar:"تابعوا حالة طلبكم لحظياً واحصلوا على تقارير مفصّلة.",ku:"Rewşa sîpariça xwe wê gavê bişopîne û raporên berfireh bistîne."},
"Türkiye Geneli Teslimat":{en:"Nationwide Delivery",de:"Landesweite Lieferung",fr:"Livraison nationale",es:"Entrega en todo el país",ru:"Доставка по всей стране",ar:"توصيل على مستوى البلاد",ku:"Şandin li Seranserê Welêt"},
"81 ile yayılan lojistik ağımızla teslimat sorunlarını ortadan kaldırıyoruz.":{en:"With our logistics network spanning 81 provinces, we eliminate delivery problems.",de:"Mit unserem Logistiknetz in 81 Provinzen beseitigen wir Lieferprobleme.",fr:"Avec notre réseau logistique couvrant 81 provinces, nous éliminons les problèmes de livraison.",es:"Con nuestra red logística que cubre 81 provincias, eliminamos los problemas de entrega.",ru:"Наша логистическая сеть в 81 провинции устраняет проблемы с доставкой.",ar:"بشبكتنا اللوجستية الممتدة على 81 محافظة، نقضي على مشكلات التسليم.",ku:"Bi tora me ya lojîstîkê ya li 81 parêzgehan belavbûyî, em pirsgirêkên şandinê ji holê radikin."},
"Müşterimiz Olun":{en:"Become a Customer",de:"Kunde werden",fr:"Devenir client",es:"Conviértase en cliente",ru:"Стать клиентом",ar:"كن عميلاً",ku:"Bibe Xerîdar"},
"Operasyonel satın alma yükünden kurtulun, bütçenizi kontrol altına alın.":{en:"Free yourself from the operational purchasing burden and take control of your budget.",de:"Befreien Sie sich von der operativen Einkaufslast und behalten Sie Ihr Budget im Griff.",fr:"Libérez-vous de la charge des achats opérationnels et maîtrisez votre budget.",es:"Libérese de la carga de las compras operativas y controle su presupuesto.",ru:"Избавьтесь от операционной нагрузки закупок и контролируйте бюджет.",ar:"تخلّصوا من عبء الشراء التشغيلي وتحكّموا في ميزانيتكم.",ku:"Xwe ji barê kirîna xebatî rizgar bike û budceya xwe bigire bin kontrolê."},
"%20'ye varan maliyet tasarrufu":{en:"Cost savings of up to 20%",de:"Kosteneinsparungen von bis zu 20 %",fr:"Jusqu'à 20 % d'économies",es:"Ahorro de costes de hasta el 20 %",ru:"Экономия до 20%",ar:"توفير في التكاليف يصل إلى 20%",ku:"Xêrkirina lêçûnan heta %20"},
"Zaman tasarrufu ve verimlilik":{en:"Time savings and efficiency",de:"Zeitersparnis und Effizienz",fr:"Gain de temps et efficacité",es:"Ahorro de tiempo y eficiencia",ru:"Экономия времени и эффективность",ar:"توفير الوقت والكفاءة",ku:"Xêrkirina dem û bikêrhatin"},
"Uzman kategori yöneticileri desteği":{en:"Support from expert category managers",de:"Unterstützung durch erfahrene Category Manager",fr:"Accompagnement par des category managers experts",es:"Apoyo de gestores de categoría expertos",ru:"Поддержка опытных категорийных менеджеров",ar:"دعم من مديري فئات خبراء",ku:"Piştgiriya rêvebirên kategoriyê yên pispor"},
"Şimdi Başvurun":{en:"Apply Now",de:"Jetzt bewerben",fr:"Postuler maintenant",es:"Solicítelo ahora",ru:"Подать заявку",ar:"قدّموا الآن",ku:"Niha Serî Lê Bide"},
"Tedarikçimiz Olun":{en:"Become Our Supplier",de:"Unser Lieferant werden",fr:"Devenez notre fournisseur",es:"Sea nuestro proveedor",ru:"Станьте нашим поставщиком",ar:"كن مورّدنا",ku:"Bibe Peydakarê Me"},
"Üretim kapasitenizi artırın, Türkiye'nin lider kurumlarına satış yapın.":{en:"Grow your production capacity and sell to Türkiye's leading institutions.",de:"Steigern Sie Ihre Produktionskapazität und verkaufen Sie an die führenden Institutionen der Türkei.",fr:"Augmentez votre capacité de production et vendez aux principales institutions de Turquie.",es:"Aumente su capacidad de producción y venda a las principales instituciones de Türkiye.",ru:"Наращивайте производственные мощности и продавайте ведущим организациям Турции.",ar:"وسّعوا طاقتكم الإنتاجية وبيعوا لكبرى مؤسّسات تركيا.",ku:"Kapasîteya xwe ya hilberînê zêde bike û ji saziyên pêşeng ên Tirkiyeyê re bifroşe."},
"Sürekli ve düzenli iş akışı":{en:"Steady and regular workflow",de:"Stetiger und regelmäßiger Auftragsfluss",fr:"Flux de travail régulier et continu",es:"Flujo de trabajo constante y regular",ru:"Постоянный и регулярный поток заказов",ar:"تدفّق عمل مستمرّ ومنتظم",ku:"Herikîna karê domdar û birêkûpêk"},
"Zamanında ve güvenli ödeme":{en:"On-time and secure payment",de:"Pünktliche und sichere Zahlung",fr:"Paiement ponctuel et sécurisé",es:"Pago puntual y seguro",ru:"Своевременная и надёжная оплата",ar:"دفع في الوقت المحدّد وآمن",ku:"Dayîna di wext de û ewledar"},
"Satış ve pazarlama maliyeti sıfır":{en:"Zero sales and marketing cost",de:"Null Vertriebs- und Marketingkosten",fr:"Coût de vente et de marketing nul",es:"Coste cero de ventas y marketing",ru:"Нулевые расходы на продажи и маркетинг",ar:"تكلفة بيع وتسويق صفرية",ku:"Lêçûna firotin û bazarê sifir"},
"Partnerlik Başvurusu":{en:"Partnership Application",de:"Partnerschaftsantrag",fr:"Demande de partenariat",es:"Solicitud de colaboración",ru:"Заявка на партнёрство",ar:"طلب شراكة",ku:"Serlêdana Hevkariyê"},
"GÜVENEN MARKALAR":{en:"BRANDS THAT TRUST US",de:"MARKEN, DIE UNS VERTRAUEN",fr:"DES MARQUES QUI NOUS FONT CONFIANCE",es:"MARCAS QUE CONFÍAN EN NOSOTROS",ru:"БРЕНДЫ, КОТОРЫЕ НАМ ДОВЕРЯЮТ",ar:"علامات تثق بنا",ku:"MARQAYÊN KU JI ME BAWER DIKIN"},
"Sıkça Sorulan Sorular":{en:"Frequently Asked Questions",de:"Häufig gestellte Fragen",fr:"Questions fréquentes",es:"Preguntas frecuentes",ru:"Часто задаваемые вопросы",ar:"الأسئلة الشائعة",ku:"Pirsên Pir Tên Pirsîn"},
"Nasıl teklif alırım?":{en:"How do I get a quote?",de:"Wie erhalte ich ein Angebot?",fr:"Comment obtenir un devis ?",es:"¿Cómo solicito un presupuesto?",ru:"Как получить предложение?",ar:"كيف أحصل على عرض سعر؟",ku:"Ez çawa pêşniyarê distînim?"},
"Web sitemizdeki teklif formunu doldurarak veya doğrudan müşteri temsilcimize talebinizi ileterek teklif alabilirsiniz. Talebiniz alındıktan sonra en kısa sürede size en uygun alternatiflerle dönüş yapıyoruz.":{en:"You can get a quote by filling in the form on our website or by sending your request directly to our representative. Once received, we get back to you as soon as possible with the best alternatives.",de:"Sie erhalten ein Angebot, indem Sie das Formular auf unserer Website ausfüllen oder Ihre Anfrage direkt an unseren Kundenbetreuer senden. Nach Eingang melden wir uns schnellstmöglich mit den besten Alternativen.",fr:"Vous pouvez obtenir un devis en remplissant le formulaire de notre site ou en envoyant votre demande directement à notre conseiller. Dès réception, nous revenons vers vous au plus vite avec les meilleures options.",es:"Puede solicitar un presupuesto rellenando el formulario de nuestra web o enviando su solicitud directamente a nuestro representante. Una vez recibida, le respondemos lo antes posible con las mejores alternativas.",ru:"Вы можете получить предложение, заполнив форму на сайте или направив запрос напрямую нашему менеджеру. После получения мы оперативно вернёмся с лучшими вариантами.",ar:"يمكنكم الحصول على عرض سعر بتعبئة النموذج في موقعنا أو بإرسال طلبكم مباشرةً إلى ممثّلنا. بعد الاستلام، نعود إليكم بأسرع وقت بأفضل البدائل.",ku:"Hûn dikarin bi tijekirina forma malpera me an jî bi şandina daxwaza xwe rasterast ji nûnerê me re pêşniyarê bistînin. Piştî wergirtinê, em di zûtirîn dem de bi alternatîfên herî baş vedigerin we."},
"Teklif ücretli mi?":{en:"Is the quote paid?",de:"Ist das Angebot kostenpflichtig?",fr:"Le devis est-il payant ?",es:"¿El presupuesto tiene coste?",ru:"Предложение платное?",ar:"هل عرض السعر مدفوع؟",ku:"Pêşniyar bi pere ye?"},
"Hayır, BERZAN üzerinden teklif toplamak tamamen ücretsizdir. Sipariş onaylanana kadar herhangi bir maliyet oluşmaz.":{en:"No, collecting quotes through BERZAN is completely free. No cost arises until the order is approved.",de:"Nein, das Einholen von Angeboten über BERZAN ist völlig kostenlos. Bis zur Auftragsbestätigung entstehen keine Kosten.",fr:"Non, la collecte de devis via BERZAN est entièrement gratuite. Aucun frais n'est engagé tant que la commande n'est pas confirmée.",es:"No, recopilar presupuestos a través de BERZAN es totalmente gratis. No hay coste alguno hasta que se aprueba el pedido.",ru:"Нет, сбор предложений через BERZAN полностью бесплатный. Никаких затрат до подтверждения заказа.",ar:"لا، جمع العروض عبر بيرزان مجاني تماماً. لا تنشأ أي تكلفة حتى تتم الموافقة على الطلب.",ku:"Na, berhevkirina pêşniyaran bi BERZAN re bi tevahî bê pere ye. Heta sîpariş neyê erêkirin tu lêçûn çênabe."},
"Hangi ürünleri tedarik ediyorsunuz?":{en:"Which products do you supply?",de:"Welche Produkte liefern Sie?",fr:"Quels produits fournissez-vous ?",es:"¿Qué productos suministran?",ru:"Какие товары вы поставляете?",ar:"ما المنتجات التي تورّدونها؟",ku:"Hûn kîjan berheman peyda dikin?"},
"Matbaa, promosyon, ambalaj, iş kıyafeti, iş güvenliği ekipmanları ve ofis kırtasiye malzemeleri başta olmak üzere tüm operasyonel ihtiyaçlarınızı tedarik ediyoruz. Özel projeleriniz için de kaynak araştırması yapmaktayız.":{en:"We supply all your operational needs, primarily printing, promotion, packaging, workwear, occupational safety equipment and office stationery. We also conduct sourcing research for your special projects.",de:"Wir liefern all Ihre betrieblichen Bedürfnisse, vor allem Druck, Werbeartikel, Verpackung, Arbeitskleidung, Arbeitsschutzausrüstung und Bürobedarf. Auch für Sonderprojekte recherchieren wir Bezugsquellen.",fr:"Nous fournissons tous vos besoins opérationnels, principalement l'impression, la promotion, l'emballage, les vêtements de travail, les équipements de sécurité et la papeterie. Nous effectuons aussi des recherches de sources pour vos projets spéciaux.",es:"Suministramos todas sus necesidades operativas, principalmente imprenta, promoción, embalaje, ropa de trabajo, equipos de seguridad y papelería. También realizamos búsqueda de fuentes para sus proyectos especiales.",ru:"Мы поставляем все операционные потребности — прежде всего полиграфию, промопродукцию, упаковку, спецодежду, СИЗ и канцелярию. Также ищем источники под ваши особые проекты.",ar:"نورّد جميع احتياجاتكم التشغيلية، وفي مقدّمتها الطباعة والترويج والتغليف وملابس العمل ومعدّات السلامة والقرطاسية المكتبية. كما نجري بحثاً عن المصادر لمشاريعكم الخاصّة.",ku:"Em hemû hewcedariyên we yên xebatî peyda dikin, di serî de çap, promosyon, pakkirin, cilên kar, amûrên ewlehiya kar û qirtasiya ofîsê. Ji bo projeyên we yên taybet jî em lêkolîna çavkaniyê dikin."},
"Teslimat ne kadar sürer?":{en:"How long does delivery take?",de:"Wie lange dauert die Lieferung?",fr:"Combien de temps prend la livraison ?",es:"¿Cuánto tarda la entrega?",ru:"Сколько занимает доставка?",ar:"كم يستغرق التسليم؟",ku:"Şandin çiqas dom dike?"},
"Teslimat süresi ürün grubuna göre değişiklik gösterir. Standart ürünler kısa sürede, özel üretim ürünler ise teklifte belirtilen takvim doğrultusunda teslim edilir.":{en:"Delivery time varies by product group. Standard products are delivered quickly, while custom-made products follow the schedule stated in the quote.",de:"Die Lieferzeit variiert je nach Produktgruppe. Standardprodukte werden schnell geliefert, Sonderanfertigungen gemäß dem im Angebot genannten Zeitplan.",fr:"Le délai de livraison varie selon le groupe de produits. Les produits standard sont livrés rapidement, les produits sur mesure selon le calendrier indiqué dans le devis.",es:"El plazo de entrega varía según el grupo de productos. Los productos estándar se entregan rápido y los de fabricación especial según el calendario indicado en la oferta.",ru:"Срок доставки зависит от группы товаров. Стандартные товары доставляются быстро, а изделия под заказ — в сроки, указанные в предложении.",ar:"يختلف وقت التسليم حسب فئة المنتج. تُسلَّم المنتجات القياسية بسرعة، أمّا المنتجات الخاصّة فحسب الجدول المذكور في العرض.",ku:"Dema şandinê li gorî koma berheman diguhere. Berhemên standard di demeke kurt de, berhemên hilberîna taybet jî li gorî bernameya di pêşniyarê de hatî diyarkirin tên şandin."},
"Minimum sipariş var mı?":{en:"Is there a minimum order?",de:"Gibt es eine Mindestbestellmenge?",fr:"Y a-t-il une commande minimale ?",es:"¿Hay un pedido mínimo?",ru:"Есть ли минимальный заказ?",ar:"هل يوجد حد أدنى للطلب؟",ku:"Sîpariça herî kêm heye?"},
"Minimum sipariş miktarları ürün kategorisine ve üretim tipine göre değişmektedir. Birçok ürün grubunda esnek miktarlar sunabilmekteyiz.":{en:"Minimum order quantities vary by product category and production type. For many product groups we can offer flexible quantities.",de:"Die Mindestbestellmengen variieren je nach Produktkategorie und Produktionsart. Für viele Produktgruppen bieten wir flexible Mengen.",fr:"Les quantités minimales varient selon la catégorie de produit et le type de production. Pour de nombreux groupes, nous proposons des quantités flexibles.",es:"Las cantidades mínimas varían según la categoría de producto y el tipo de producción. En muchos grupos ofrecemos cantidades flexibles.",ru:"Минимальные объёмы зависят от категории товара и типа производства. Для многих групп возможны гибкие объёмы.",ar:"تختلف كميّات الطلب الدنيا حسب فئة المنتج ونوع الإنتاج. ولكثير من الفئات نوفّر كميّات مرنة.",ku:"Mîqdarên sîpariça herî kêm li gorî kategoriya berhem û cureyê hilberînê diguherin. Ji bo gelek koman em dikarin mîqdarên nerm pêşkêş bikin."},
"Ödeme/vade seçenekleri neler?":{en:"What are the payment/term options?",de:"Welche Zahlungs-/Zahlungszieloptionen gibt es?",fr:"Quelles sont les options de paiement/échéance ?",es:"¿Qué opciones de pago/plazo hay?",ru:"Какие варианты оплаты и отсрочки?",ar:"ما خيارات الدفع/الأجل؟",ku:"Bijarên dayîn/mohletê çi ne?"},
"Nakit ödeme, kredi kartı ve kurumsal cari hesap vadesi gibi çeşitli seçenekler sunuyoruz. Vade seçenekleri firma limitlerine ve proje detaylarına göre belirlenmektedir.":{en:"We offer various options such as cash, credit card and corporate current-account terms. Term options are set according to company limits and project details.",de:"Wir bieten verschiedene Optionen wie Barzahlung, Kreditkarte und Firmen-Kontokorrentziel. Die Zahlungsziele richten sich nach Firmenlimits und Projektdetails.",fr:"Nous proposons diverses options : espèces, carte bancaire et échéances sur compte courant entreprise. Les échéances sont fixées selon les limites de l'entreprise et les détails du projet.",es:"Ofrecemos diversas opciones como efectivo, tarjeta de crédito y plazos en cuenta corriente corporativa. Los plazos se fijan según los límites de la empresa y los detalles del proyecto.",ru:"Мы предлагаем различные варианты: наличные, банковская карта и отсрочка по корпоративному счёту. Условия отсрочки определяются лимитами компании и деталями проекта.",ar:"نقدّم خيارات متنوّعة مثل الدفع النقدي والبطاقة الائتمانية وأجل الحساب الجاري للشركات. تُحدَّد خيارات الأجل وفق حدود الشركة وتفاصيل المشروع.",ku:"Em bijarên cuda yên wek dayîna neqit, qerta krediyê û mohleta hesabê cari yê korporatîf pêşkêş dikin. Bijarên mohletê li gorî sînorên fîrmayê û hûragahiyên projeyê tên diyarkirin."},
"Tedarik ihtiyacınızı konuşalım":{en:"Let's talk about your supply needs",de:"Sprechen wir über Ihren Bedarf",fr:"Parlons de vos besoins d'approvisionnement",es:"Hablemos de sus necesidades de suministro",ru:"Обсудим ваши потребности в снабжении",ar:"لنتحدّث عن احتياجات التوريد لديكم",ku:"Werin em li ser hewcedariya we ya peydakirinê biaxivin"},
"Talebinizi iletin, uzman ekibimiz en uygun teklifi hızlıca sunsun. Teklif almak ücretsizdir.":{en:"Send us your request and let our expert team quickly present the best quote. Getting a quote is free.",de:"Senden Sie uns Ihre Anfrage und unser Expertenteam unterbreitet Ihnen schnell das beste Angebot. Ein Angebot ist kostenlos.",fr:"Envoyez votre demande et notre équipe d'experts vous présentera rapidement la meilleure offre. Le devis est gratuit.",es:"Envíe su solicitud y nuestro equipo experto le presentará rápidamente la mejor oferta. Solicitar presupuesto es gratis.",ru:"Отправьте заявку, и наша команда быстро предложит лучшее предложение. Запрос бесплатен.",ar:"أرسلوا طلبكم ودعوا فريقنا الخبير يقدّم لكم أفضل عرض بسرعة. الحصول على عرض السعر مجاني.",ku:"Daxwaza xwe bişîne, bila tîma me ya pispor bilez pêşniyara herî baş pêşkêş bike. Pêşniyar bistînin bê pere ye."},
"Bize Ulaşın":{en:"Contact Us",de:"Kontaktieren Sie uns",fr:"Contactez-nous",es:"Contáctenos",ru:"Свяжитесь с нами",ar:"تواصلوا معنا",ku:"Bi Me Re Têkilî Daynin"},
"Kurumsal firmalar için tek noktadan B2B tedarik ortağı. İhtiyacınız olan ürünleri en uygun fiyata buluruz.":{en:"A single-point B2B supply partner for corporate companies. We find the products you need at the best price.",de:"Ein zentraler B2B-Beschaffungspartner für Unternehmen. Wir finden die Produkte, die Sie brauchen, zum besten Preis.",fr:"Un partenaire d'approvisionnement B2B à point unique pour les entreprises. Nous trouvons les produits dont vous avez besoin au meilleur prix.",es:"Un socio de suministro B2B de punto único para empresas. Encontramos los productos que necesita al mejor precio.",ru:"Единый B2B-партнёр по снабжению для компаний. Найдём нужные товары по лучшей цене.",ar:"شريك توريد B2B من نقطة واحدة للشركات. نجد لكم المنتجات التي تحتاجونها بأفضل سعر.",ku:"Ji bo şirketên korporatîf hevkarê peydakirina B2B ji yek xalê. Em berhemên hewcedariya we bi bihayê herî guncaw dibînin."},
"Kurumsal":{en:"Corporate",de:"Unternehmen",fr:"Entreprise",es:"Corporativo",ru:"Компания",ar:"الشركة",ku:"Korporatîf"},
"Hizmetler":{en:"Services",de:"Leistungen",fr:"Services",es:"Servicios",ru:"Услуги",ar:"الخدمات",ku:"Xizmet"},
"© 2025 BERZAN. Tüm Hakları Saklıdır.":{en:"© 2025 BERZAN. All rights reserved.",de:"© 2025 BERZAN. Alle Rechte vorbehalten.",fr:"© 2025 BERZAN. Tous droits réservés.",es:"© 2025 BERZAN. Todos los derechos reservados.",ru:"© 2025 BERZAN. Все права защищены.",ar:"© 2025 بيرزان. جميع الحقوق محفوظة.",ku:"© 2025 BERZAN. Hemû maf parastî ne."},
"← Ana Sayfa":{en:"← Home",de:"← Startseite",fr:"← Accueil",es:"← Inicio",ru:"← Главная",ar:"← الرئيسية",ku:"← Rûpela Sereke"},
"Ana Sayfa":{en:"Home",de:"Startseite",fr:"Accueil",es:"Inicio",ru:"Главная",ar:"الرئيسية",ku:"Rûpela Sereke"},
"MÜŞTERİMİZ OLUN":{en:"BECOME A CUSTOMER",de:"KUNDE WERDEN",fr:"DEVENIR CLIENT",es:"CONVIÉRTASE EN CLIENTE",ru:"СТАТЬ КЛИЕНТОМ",ar:"كن عميلاً",ku:"BIBE XERÎDAR"},
"Teklif alın, alımlarınızı kolaylaştırın":{en:"Get a quote, simplify your purchasing",de:"Angebot anfordern, Ihren Einkauf vereinfachen",fr:"Demandez un devis, simplifiez vos achats",es:"Solicite un presupuesto y simplifique sus compras",ru:"Получите предложение и упростите закупки",ar:"اطلبوا عرض سعر وبسّطوا مشترياتكم",ku:"Pêşniyarê bistîne, kirînên xwe hêsantir bike"},
"Tek talep gönderin; tedarikçi ağımızdan en uygun teklifleri toplayıp size sunalım. Tek muhatap, tek fatura ve net fiyatlandırma ile satın alma yükünüzü hafifletiyoruz.":{en:"Send a single request; we collect the best quotes from our supplier network and present them to you. With one contact, one invoice and clear pricing, we ease your purchasing burden.",de:"Senden Sie eine einzige Anfrage; wir holen die besten Angebote aus unserem Lieferantennetz ein und legen sie Ihnen vor. Mit einem Ansprechpartner, einer Rechnung und klarer Preisgestaltung erleichtern wir Ihren Einkauf.",fr:"Envoyez une seule demande ; nous collectons les meilleures offres de notre réseau et vous les présentons. Avec un interlocuteur, une facture et une tarification claire, nous allégeons vos achats.",es:"Envíe una sola solicitud; recopilamos las mejores ofertas de nuestra red y se las presentamos. Con un interlocutor, una factura y precios claros, aliviamos su carga de compras.",ru:"Отправьте один запрос — мы соберём лучшие предложения из нашей сети и представим их вам. Один контакт, один счёт и прозрачные цены облегчают закупки.",ar:"أرسلوا طلباً واحداً؛ نجمع أفضل العروض من شبكة مورّدينا ونقدّمها لكم. بجهة اتصال واحدة وفاتورة واحدة وتسعير واضح، نخفّف عبء الشراء عنكم.",ku:"Yek daxwazê bişîne; em ji tora xwe ya peydakaran pêşniyarên herî baş berhev dikin û pêşkêşî we dikin. Bi yek navbeynkar, yek fatûre û bihayê zelal, em barê kirîna we sivik dikin."},
"Çoklu teklifle en uygun fiyat":{en:"Best price with multiple quotes",de:"Bester Preis durch mehrere Angebote",fr:"Meilleur prix grâce à plusieurs devis",es:"Mejor precio con múltiples ofertas",ru:"Лучшая цена за счёт нескольких предложений",ar:"أفضل سعر عبر عروض متعدّدة",ku:"Bi gelek pêşniyaran bihayê herî guncaw"},
"Tek muhatap, tek fatura kolaylığı":{en:"The ease of one contact, one invoice",de:"Der Komfort von einem Ansprechpartner, einer Rechnung",fr:"La simplicité d'un interlocuteur, une facture",es:"La comodidad de un interlocutor, una factura",ru:"Удобство одного контакта и одного счёта",ar:"سهولة جهة اتصال واحدة وفاتورة واحدة",ku:"Hêsaniya yek navbeynkar, yek fatûre"},
"Talepten teslime kadar tam takip":{en:"Full tracking from request to delivery",de:"Vollständige Verfolgung von der Anfrage bis zur Lieferung",fr:"Suivi complet de la demande à la livraison",es:"Seguimiento completo desde la solicitud hasta la entrega",ru:"Полное отслеживание от заявки до доставки",ar:"متابعة كاملة من الطلب حتى التسليم",ku:"Şopandina temam ji daxwazê heta şandinê"},
"Teklif almak tamamen ücretsiz":{en:"Getting a quote is completely free",de:"Ein Angebot einzuholen ist völlig kostenlos",fr:"Obtenir un devis est entièrement gratuit",es:"Solicitar un presupuesto es totalmente gratis",ru:"Получить предложение совершенно бесплатно",ar:"الحصول على عرض السعر مجاني تماماً",ku:"Pêşniyar bistînin bi tevahî bê pere ye"},
"WhatsApp'tan Yazın":{en:"Message on WhatsApp",de:"Per WhatsApp schreiben",fr:"Écrire sur WhatsApp",es:"Escríbanos por WhatsApp",ru:"Написать в WhatsApp",ar:"راسلونا على واتساب",ku:"Li ser WhatsApp Binivîse"},
"Teklif Formu":{en:"Quote Form",de:"Angebotsformular",fr:"Formulaire de devis",es:"Formulario de presupuesto",ru:"Форма запроса",ar:"نموذج طلب عرض السعر",ku:"Forma Pêşniyarê"},
"Ad Soyad":{en:"Full Name",de:"Vor- und Nachname",fr:"Nom et prénom",es:"Nombre y apellidos",ru:"Имя и фамилия",ar:"الاسم الكامل",ku:"Nav û Paşnav"},
"Firma":{en:"Company",de:"Firma",fr:"Société",es:"Empresa",ru:"Компания",ar:"الشركة",ku:"Fîrme"},
"E-posta":{en:"Email",de:"E-Mail",fr:"E-mail",es:"Correo electrónico",ru:"Эл. почта",ar:"البريد الإلكتروني",ku:"E-name"},
"Telefon":{en:"Phone",de:"Telefon",fr:"Téléphone",es:"Teléfono",ru:"Телефон",ar:"الهاتف",ku:"Telefon"},
"Talebiniz":{en:"Your Request",de:"Ihre Anfrage",fr:"Votre demande",es:"Su solicitud",ru:"Ваш запрос",ar:"طلبكم",ku:"Daxwaza We"},
"Talebi Gönder":{en:"Send Request",de:"Anfrage senden",fr:"Envoyer la demande",es:"Enviar solicitud",ru:"Отправить заявку",ar:"إرسال الطلب",ku:"Daxwazê Bişîne"},
"TEDARİKÇİMİZ OLUN":{en:"BECOME OUR SUPPLIER",de:"UNSER LIEFERANT WERDEN",fr:"DEVENEZ NOTRE FOURNISSEUR",es:"SEA NUESTRO PROVEEDOR",ru:"СТАНЬТЕ НАШИМ ПОСТАВЩИКОМ",ar:"كن مورّدنا",ku:"BIBE PEYDAKARÊ ME"},
"Kurumsal müşteri ağımıza katılın":{en:"Join our corporate customer network",de:"Treten Sie unserem Firmenkundennetzwerk bei",fr:"Rejoignez notre réseau de clients entreprises",es:"Únase a nuestra red de clientes corporativos",ru:"Присоединяйтесь к нашей сети корпоративных клиентов",ar:"انضمّوا إلى شبكة عملائنا المؤسّسيين",ku:"Tevlî tora me ya xerîdarên korporatîf bibe"},
"Üretici veya tedarikçiyseniz, BERZAN üzerinden kurumsal müşterilere ulaşın. Sürekli iş akışı, zamanında ödeme ve sıfır pazarlama maliyetiyle büyüyün.":{en:"If you are a manufacturer or supplier, reach corporate customers through BERZAN. Grow with steady workflow, on-time payment and zero marketing cost.",de:"Wenn Sie Hersteller oder Lieferant sind, erreichen Sie über BERZAN Firmenkunden. Wachsen Sie mit stetigem Auftragsfluss, pünktlicher Zahlung und null Marketingkosten.",fr:"Fabricant ou fournisseur, atteignez des clients entreprises via BERZAN. Développez-vous avec un flux régulier, des paiements ponctuels et zéro coût marketing.",es:"Si es fabricante o proveedor, llegue a clientes corporativos a través de BERZAN. Crezca con flujo constante, pagos puntuales y coste de marketing cero.",ru:"Если вы производитель или поставщик, выходите на корпоративных клиентов через BERZAN. Растите с постоянным потоком заказов, своевременной оплатой и нулевыми затратами на маркетинг.",ar:"إن كنتم مصنّعاً أو مورّداً، فاصلوا إلى العملاء المؤسّسيين عبر بيرزان. انموا بتدفّق عمل مستمرّ ودفع في موعده وتكلفة تسويق صفرية.",ku:"Heke hûn hilberîner an peydakar bin, bi rêya BERZAN bigihîjin xerîdarên korporatîf. Bi herikîna karê domdar, dayîna di wext de û lêçûna bazarê ya sifir mezin bibin."},
"Sürekli ve düzenli yeni iş hacmi":{en:"Steady and regular new business volume",de:"Stetiges und regelmäßiges neues Geschäftsvolumen",fr:"Volume d'affaires nouveau, régulier et continu",es:"Volumen de negocio nuevo, constante y regular",ru:"Постоянный и регулярный объём новых заказов",ar:"حجم أعمال جديد مستمرّ ومنتظم",ku:"Mîqdara karê nû ya domdar û birêkûpêk"},
"Kurumsal müşterilere doğrudan erişim":{en:"Direct access to corporate customers",de:"Direkter Zugang zu Firmenkunden",fr:"Accès direct aux clients entreprises",es:"Acceso directo a clientes corporativos",ru:"Прямой доступ к корпоративным клиентам",ar:"وصول مباشر إلى العملاء المؤسّسيين",ku:"Gihîştina rasterast bo xerîdarên korporatîf"},
"Tedarikçi Başvuru Formu":{en:"Supplier Application Form",de:"Lieferanten-Bewerbungsformular",fr:"Formulaire de candidature fournisseur",es:"Formulario de solicitud de proveedor",ru:"Анкета поставщика",ar:"نموذج طلب المورّد",ku:"Forma Serlêdana Peydakar"},
"Hangi ürün/hizmetleri sağlıyorsunuz?":{en:"Which products/services do you provide?",de:"Welche Produkte/Leistungen bieten Sie an?",fr:"Quels produits/services proposez-vous ?",es:"¿Qué productos/servicios ofrece?",ru:"Какие товары/услуги вы предоставляете?",ar:"ما المنتجات/الخدمات التي تقدّمونها؟",ku:"Hûn kîjan berhem/xizmetan peyda dikin?"},
"Başvuruyu Gönder":{en:"Submit Application",de:"Bewerbung senden",fr:"Envoyer la candidature",es:"Enviar solicitud",ru:"Отправить заявку",ar:"إرسال الطلب",ku:"Serlêdanê Bişîne"},
"Tedarik süreçlerinizi birlikte optimize edelim. Talebinizi iletin, uzman ekibimiz en kısa sürede dönüş yapsın.":{en:"Let's optimize your procurement processes together. Send your request and our expert team will get back to you shortly.",de:"Optimieren wir gemeinsam Ihre Beschaffungsprozesse. Senden Sie Ihre Anfrage und unser Expertenteam meldet sich in Kürze.",fr:"Optimisons ensemble vos processus d'achat. Envoyez votre demande et notre équipe d'experts vous répondra rapidement.",es:"Optimicemos juntos sus procesos de compra. Envíe su solicitud y nuestro equipo experto le responderá en breve.",ru:"Оптимизируем ваши закупки вместе. Отправьте заявку, и наша команда вскоре ответит.",ar:"لنحسّن معاً عمليات التوريد لديكم. أرسلوا طلبكم وسيعود إليكم فريقنا الخبير قريباً.",ku:"Werin em bi hev re pêvajoyên we yên peydakirinê baştir bikin. Daxwaza xwe bişîne, tîma me ya pispor wê zû bersivê bide."},
"TELEFON / WHATSAPP":{en:"PHONE / WHATSAPP",de:"TELEFON / WHATSAPP",fr:"TÉLÉPHONE / WHATSAPP",es:"TELÉFONO / WHATSAPP",ru:"ТЕЛЕФОН / WHATSAPP",ar:"الهاتف / واتساب",ku:"TELEFON / WHATSAPP"},
"E-POSTA":{en:"EMAIL",de:"E-MAIL",fr:"E-MAIL",es:"CORREO",ru:"ЭЛ. ПОЧТА",ar:"البريد الإلكتروني",ku:"E-NAME"},
"Yurt dışından / global ulaşım için":{en:"For international / global contact",de:"Für internationale / globale Kontakte",fr:"Pour les contacts internationaux / mondiaux",es:"Para contacto internacional / global",ru:"Для международных обращений",ar:"للتواصل من الخارج / عالمياً",ku:"Ji bo têkiliya navneteweyî / global"},
"Türkiye içinden ulaşım için":{en:"For contact within Türkiye",de:"Für Kontakte innerhalb der Türkei",fr:"Pour les contacts en Turquie",es:"Para contacto dentro de Türkiye",ru:"Для обращений внутри Турции",ar:"للتواصل من داخل تركيا",ku:"Ji bo têkiliya ji hundirê Tirkiyeyê"},
"Talep Formu":{en:"Request Form",de:"Anfrageformular",fr:"Formulaire de demande",es:"Formulario de solicitud",ru:"Форма заявки",ar:"نموذج الطلب",ku:"Forma Daxwazê"},
"Talep Türü":{en:"Request Type",de:"Anfrageart",fr:"Type de demande",es:"Tipo de solicitud",ru:"Тип заявки",ar:"نوع الطلب",ku:"Cureyê Daxwazê"},
"Mesaj":{en:"Message",de:"Nachricht",fr:"Message",es:"Mensaje",ru:"Сообщение",ar:"الرسالة",ku:"Peyam"}
  };

  // --- Çevrilebilir metin düğümlerini topla, orijinali sakla ---
  var nodes = [];
  function shouldSkip(node) {
    var p = node.parentElement;
    while (p) {
      var tag = p.tagName;
      if (tag === "SCRIPT" || tag === "STYLE" || tag === "SELECT" || tag === "OPTION" || tag === "TEXTAREA") return true;
      var c = " " + (typeof p.className === "string" ? p.className : "") + " ";
      if (c.indexOf(" material-symbols-outlined ") > -1 || c.indexOf(" notranslate ") > -1 || c.indexOf(" ms ") > -1) return true;
      p = p.parentElement;
    }
    return false;
  }
  function collect() {
    nodes = [];
    var w = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null);
    var n;
    while ((n = w.nextNode())) {
      if (n.nodeValue && n.nodeValue.trim() && !shouldSkip(n)) {
        nodes.push({ node: n, orig: n.nodeValue });
      }
    }
  }
  function apply(lang) {
    nodes.forEach(function (it) {
      if (lang === "tr") { if (it.node.nodeValue !== it.orig) it.node.nodeValue = it.orig; return; }
      var key = it.orig.trim();
      var entry = T[key];
      var tr = entry && entry[lang];
      if (tr != null) {
        var lead = it.orig.match(/^\s*/)[0], trail = it.orig.match(/\s*$/)[0];
        it.node.nodeValue = lead + tr + trail;
      } else if (it.node.nodeValue !== it.orig) {
        it.node.nodeValue = it.orig; // çeviri yoksa Türkçe kalır
      }
    });
    document.documentElement.lang = lang;
    document.documentElement.dir = RTL[lang] ? "rtl" : "ltr";
  }

  function saved() { try { return localStorage.getItem("berzanLang") || "tr"; } catch (e) { return "tr"; } }
  function store(l) { try { localStorage.setItem("berzanLang", l); } catch (e) {} }

  // --- Dil seçici (dropdown) enjekte et ---
  function buildSelect(cls) {
    var sel = document.createElement("select");
    sel.className = "langSelect notranslate " + cls;
    sel.setAttribute("aria-label", "Dil / Language");
    sel.innerHTML = LANGS.map(function (l) { return '<option value="' + l[0] + '">' + l[1] + "</option>"; }).join("");
    return sel;
  }
  function iconWrap(extra) {
    var w = document.createElement("div");
    w.className = "notranslate " + extra;
    w.innerHTML = '<span class="material-symbols-outlined text-xl">language</span>';
    return w;
  }
  var nav = document.getElementById("main-nav");
  if (nav) {
    var toggle = document.getElementById("navToggle");
    var w = iconWrap("hidden md:flex items-center gap-1 text-on-primary mr-1");
    w.appendChild(buildSelect("bg-primary-container text-on-primary text-sm rounded-md pl-1 pr-2 py-1.5 border border-white/15 cursor-pointer focus:outline-none"));
    if (toggle && toggle.parentNode) toggle.parentNode.insertBefore(w, toggle); else nav.appendChild(w);
  }
  var mm = document.getElementById("mobileMenu");
  if (mm) {
    var navc = mm.querySelector("nav") || mm;
    var mw = iconWrap("flex items-center gap-2 mt-3 pt-3 border-t border-white/10 text-on-primary");
    mw.appendChild(buildSelect("flex-1 bg-primary-container text-on-primary rounded-md px-3 py-2.5 border border-white/15"));
    navc.appendChild(mw);
  }

  collect();
  var cur = saved();
  if (cur !== "tr") apply(cur);
  document.querySelectorAll(".langSelect").forEach(function (sel) {
    sel.value = cur;
    sel.addEventListener("change", function () {
      var l = this.value; store(l); apply(l);
      document.querySelectorAll(".langSelect").forEach(function (s) { s.value = l; });
      if (mm) mm.classList.add("hide");
    });
  });
})();
